name: publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install -g
    - run: npm start
    - run: npm test
    - run: npm login ${{ secrets.NPM_TOKEN }}
    - run: npm publish
